import os

API_ID = int(os.environ.get("API_ID", "12197477"))
API_HASH = os.environ.get("API_HASH", "ac077d8acc256685720b14eba02d8d11")
BOT_TOKEN = os.environ.get("BOT_TOKEN", "7012628239:AAGaWUbfSzYRb3zXm0o0IcSAM4-JVLklwTc")
BOT_USERNAME = os.environ.get("BOT_USERNAME", "raj_ebook_bot")
DB_CHANNEL = int(os.environ.get("DB_CHANNEL", "-1001811791698"))
SHORTENER_WEBSITE = os.environ.get('SHORTENER_WEBSITE', "bzearn.com")
SHORTENER_API = os.environ.get('SHORTENER_API', "e34b7c9d99027bf57dc8a1aa0fcb1027a2b50ea1")
BOT_OWNER = int(os.environ.get("BOT_OWNER", "1030335104"))
DATABASE_URL = os.environ.get("DATABASE_URL", "mongodb+srv://ttttechnicalaks7:filestorebotclone@cluster0.ch7domc.mongodb.net/?retryWrites=true&w=majority")
AUTH_CHANNEL = os.environ.get("UPDATES_CHANNEL", "-1001831955243")
LOG_CHANNEL = int(os.environ.get("LOG_CHANNEL", "-1001769642119"))
FORWARD_AS_COPY = bool(os.environ.get("FORWARD_AS_COPY", False))
BROADCAST_AS_COPY = bool(os.environ.get("BROADCAST_AS_COPY", True))
BANNED_USERS = set(int(x) for x in os.environ.get("BANNED_USERS", "").split())
BANNED_CHAT_IDS = list(set(int(x) for x in os.environ.get("BANNED_CHAT_IDS", "").split()))
OTHER_USERS_CAN_SAVE_FILE = bool(os.environ.get("OTHER_USERS_CAN_SAVE_FILE", True))
SUPPORT_GROUP_LINK = os.environ.get("SUPPORT_GROUP_LINK", "https://t.me/FilmyFundas")
UPDATES_CHANNEL_LINK = os.environ.get("UPDATES_CHANNEL_LINK", "https://t.me/Imdb_updates")
BATCH_CHANNEL = int(os.environ.get("BATCH_CHANNEL", "-1001969537424"))
